### ISSUE TITLE
README.md should describe two expected src directory layouts

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/sbt-crossproject#15]
Please consider having README.md describe, early on, the
expected source directory layout.  This is especially
tricky for a reader because there two layouts are used.

Reading from the top down, the first encountered layout
is for the trio project. If I understand correctly, the
 `  .crossType(CrossType.Pure) // [Pure, Full, Dummy], default: CrossType.Full `
causes the bar/.js, bar/.jvm, bar/native, shared, form to be used. Since
these are hidden directories, it makes it exceedingly hard to 
figure out.

Since I like prove out my understanding, I usually start simple
and work my way to more complex.  I jumped into the second,
duo example before I attempted the trio example.  It took 
more work than I expected, but I figured out the expected
bar/jvm, bar/native, shared directory structure.  This gives
nice, visible directories.  

When I extended my duo project to the trio project
described in the README.md, sbt could no longer
find my source code.  After ratting around, I discovered
that this is because the duo project defaulted to 'CrossType.Full'.
The trio project had an explicit 'CrossType.Pure', which expected
a different source directory structure.

As both scala-cross & my understanding of it mature, I hope
to understand when one would use a Full & when one would
use a Pure.  For now, I am using Full seems to work, so I
am using it to allow me to see my directories.

The good ascii art in file CrossType.scala helped me get the
trio project up and running.  Adding that art to the README.md
would, I believe, ease the way of other early & potential adopters.

Thank you for considering this suggestion. As always, thank you
for sbt-cross. I have learned from following the README.md.

Lee

**Comment by MasseGuillaume** [comment]
This guy gave it a shot. What do you think?
https://github.com/scala-native/sbt-cross/pull/19/commits/bb595ac71a5673a890398e1b9285a869e26f34ba

**Comment by LeeTibbert** [comment]
Thank you for asking my opinion.  

#### First approximation:  
    
I think bb595ac71a5673a890398e1b9285a869e26f34ba is a useful contribution and a good base for evolution. The perfect is the enemy of the done & useful. Thank you, @rom1dep

#### Second approximation

* I would probably add a "NOTE WELL the leading dot" to the
```
   ├── .js
   ├── .jvm
   ├── .native
```
* It would be nice to explain the intended purpose/use of the .mumble
  directories.  I have no clue.

* It would be nice to mention which cross type is the default & why.

* If CrossType.Full is the default, I would introduce it first.

*  I am loath to reveal the limits of my understanding to the world, but 
   I do not understand what the section at the bottom is trying to say. 
   I will blame the hour for my shortcoming .,,
```
 `.crossType({/*custom*/})`
+
+One can easily extend CrossType and provide a custom tree structure.
```
Perhaps the author's intent can be realized by moving the last line _way_ 
earlier & providing an example at the bottom .crossType(CrossType.Custom)
```
+sbt-cross provides  3 implementations, described below, of the CrossType class that one can
+pass as `.crossType` parameter: CrossType.Full, CrossType.Pure, CrossType.Dummy.
CrossType.Full is the default if .crossType() is given no argument.

+One can easily extend CrossType to provide a custom directory tree structure.
```

Putting my actions where my mouth/typing is, I could do a PR  after bb595ac71a5673a890398e1b9285a869e26f34ba  is merged.  

#### Third approximation, picky level.

*  I read for concept, not to as a copy editor, but the line
```
 This layout is preferred for codebases which do not contain any platform-specific code.
```
jumped out at me. Please consider something like the more direct 
```
This layout is preferred for codebases which contain no platform-specific code.
```

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/sbt-crossproject/pull/39
