### ISSUE TITLE
Testing doesn't use scala-native compiler

### ISSUE THREAD

**Issue by colinrgodsey** [scala-native/sbt-crossproject#30]
I feel like there has to be a way to get it to work, but at least right now... I cannot figure out how to get the test phase of a project to correctly use the scala-native compiler. I've tried using the utest framework, as well as just a 'main' based entry point in the test project (jsonNative/test:run) and they both yield the same result. 

Looks like its missing some classes, then for the ones it does find, it runs into the 'undefined' stubs that the compiler should be able to handle. jsonNative/run works just fine. 

EDIT: This is a cross-compile project with scala/scala-js/scala-native, the utest framework works just fine for scala-js and scala.

Here's the branch for my project I'm having issues with:
https://github.com/MediaMath/scala-json/tree/2.12.x

```
> ++2.11.8
> jsonNative/test
...
[info]                  		scala.scalanative.runtime.UndefinedBehaviorError
[info] scala.scalanative.runtime.package$.undefined(package.scala:9)
...
[info] java.lang.NoClassDefFoundError: Could not initialize class scala.scalanative.native.Tag$
```

SBT 0.13.13

addSbtPlugin("org.scala-js"     % "sbt-scalajs"              % "0.6.14")
addSbtPlugin("org.scala-native" % "sbt-crossproject"         % "0.1.0")
addSbtPlugin("org.scala-native" % "sbt-scalajs-crossproject" % "0.1.0")
addSbtPlugin("org.scala-native" % "sbt-scala-native"         % "0.1.0")

**Comment by colinrgodsey** [comment]
Here's the branch for my project I'm having issues with:

https://github.com/MediaMath/scala-json/tree/2.12.x

**Comment by densh** [comment]
Hi @colinrgodsey, thanks for the report, it's caused by https://github.com/scala-native/scala-native/issues/339 and is an issue with Scala Native, not sbt-crossproject.
