### ISSUE TITLE
Cross-publishing problems

### ISSUE THREAD

**Issue by tindzk** [scala-native/sbt-crossproject#36]
I am attempting to cross-build and publish a project for all three architectures.

When I run `sbt +publishLocal`, sbt also publishes it for 2.10. In Scala.js, the [manual](https://www.scala-js.org/doc/project/cross-build.html) advises to define a `root` project. When I do so, cross-publishing works for all projects but Scala Native (it doesn't respect the overridden `scalaVersion` and uses the 2.12 version instead).

Also, I needed to specify the root path with `.in(file("."))`, but according to the README it should also work without.

There are test cases in my `shared` sub-project and `sbt test` tries to compile them for Scala Native. As there is no testing interface for Scala Native, I expected the tests to be ignored altogether.

You can find my latest `build.sbt` [here](https://github.com/sparsetech/pine/blob/master/build.sbt).

**Comment by nadavwr** [comment]
I ran across this yesterday. SBT insisted on building 2.10 for Scala Native.
As a workaround I ended up publishing each version individually from SBT command line:
```
++2.12.2
fooJVM/publishLocal
++2.11.11
fooJVM/publishLocal
fooNative/publishLocal
```
The above can be automated with `commands += Command.command...` from root project,  or `addCommandAlias`.

Regarding `.in(file("."))`: `CrossType.Full` (the default) creates a project for each platform and a shared project, all under subdirectories—no actual project is created at root. This leaves the default root project in place, or allows you do define your own root project. This is mostly harmless, but seeing two `in(file("."))` in two project definitions is very confusing at first glance.

**Comment by tindzk** [comment]
Thanks! As for ignoring the tests, the following workaround can be used:

```scala
project.nativeSettings(
  excludeFilter in Test := "*"
)
```

**Comment by densh** [comment]
@tindzk Did the suggestion above resolve your problem? It seems to be an issue unrelated to sbt-crossproject.

**Comment by tindzk** [comment]
For the time being, I publish the dependencies manually as per @nadavwr's suggestion. However, it would be preferable if `+publishLocal` respected the overridden [`crossScalaVersions` value](https://github.com/sparsetech/pine/blob/master/build.sbt#L86) in `nativeSettings`.

**Comment by sjrd** [comment]
> However, it would be preferable if +publishLocal respected the overridden crossScalaVersions value in nativeSettings.

That is a known limitation of sbt's `+`. Scala Native cannot do anything about it.

> This is also problematic in conjunction with Travis CI because ++2.12.2 test will be run on all architectures, including Scala Native.

You can run `++2.12.2 someJVMProject/test someOtherJVMProject/test` instead. Anyway, again Scala Native cannot do anything about it.

**Comment by tindzk** [comment]
I see. Thanks for the clarifications!
