### ISSUE TITLE
Build and publish for sbt 1.0.0-RC2

### ISSUE THREAD

**Issue by sjrd** [scala-native/sbt-crossproject#48]
We need to upgrade Scala.js to sbt 1.0.0-RC2 to test it for potential critical regressions. Of course now we need sbt-crossproject to be built for 1.0.0-RC2 for that.

See also https://github.com/scala-js/scala-js/issues/3065

**Comment by xuwei-k** [comment]
- https://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-native/sbt-crossproject/scala_2.12/sbt_1.0/
- https://bintray.com/scala-native/sbt-plugins/sbt-crossproject/0.2.1

**Comment by sjrd** [comment]
Yes, right, this should be closed. Also see #51.
