### ISSUE TITLE
Publish sbt-scalajs-crossproject 0.2.1 for sbt 1.0

### ISSUE THREAD

**Issue by fthomas** [scala-native/sbt-crossproject#53]
It seems that only sbt-crossproject 0.2.1 is available for sbt 1.0 but not sbt-scalajs-crossproject:
 * http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-native/sbt-scalajs-crossproject/
 * http://dl.bintray.com/sbt/sbt-plugin-releases/org.scala-native/sbt-crossproject/

Should sbt-scalajs-crossproject be available for sbt 1.0 too?

**Comment by sjrd** [comment]
We should publish it, yes. I think there was a difficulty due to https://github.com/sbt/sbt/issues/3393, but that can be worked around, so we should be able to publish sbt-scalajs-crossproject for sbt 1.0.

**Comment by densh** [comment]
Fixed in 0.2.2

**Comment by fthomas** [comment]
Great, thanks a lot!
